### ISSUE TITLE
Not actually (fully) compatible with Baubles

### ISSUE THREAD

**Issue by MechanosG** [PfisterFactor/QuickerCrafting#23]
If you click the Baubles icon from the QuickerCrafting inventory menu (doesn't matter if you open QC from the icon or from hotkey), it "appears" like Baubles is working.  You see the baubles inventory screen and slots, and it appears that you can interact with them.  But attempting to do so then exiting the Baubles screen, you find out the changes didn't actually save.  Inventory icons start glitching out (not showing what's actually in that slot), and occasionally you even crash.

What you'd expect it to do:
In my modpack, I disabled the vanilla inventory hotkey so that QuickerCrafting would be seen by new players without an explanation.  What I expected, is for the Baubles button to allow Baubles access like the vanilla inventory screen.

What it actually did (bugs only):
Equipping and unequipping of Baubles items isn't saved.  Inventory glitches out, items pop into the wrong slots, etc.  If you open Baubles from the vanilla inventory window though, everything works fine, even with QuickerCrafting installed.

Steps to reproduce (bugs only):
Install QuickerCrafting, Baubles, and Mine and Slash.  Create a survival world and kill some mobs 'till you get a few baubles items (I wasn't using starter equipment, so just in case might wanna use generated mob loot).  Open the QuickerCrafting menu, click the circle icon to open the Baubles inventory, then try to equip or unequip some Baubles items.  Afterwards, exit the Baubles screen, then re-open your inventory, and check the Baubles slots you tried to change.

Crash log (use pastebin):
https://pastebin.com/S5PmdLzm

Additional info can also be found here https://github.com/RobertSkalko/Mine-and-Slash/issues/144

**Comment by PfisterFactor** [comment]
I think the code just opens the window on the client. I forgot to send a request to the server to open the Baubles GUI. Ill try making a quick patch.

**Comment by MechanosG** [comment]
Just tested the update.  So far it seems to be working.  Thanks :)
